
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // CLI commands (migrate, db execute, studio) must use the session-mode
  // connection (DIRECT_URL, pooler port 5432): Prisma Migrate takes advisory
  // locks that transaction pooling (port 6543) cannot hold. Falls back to
  // DATABASE_URL for environments without a pooler (docker-compose).
  datasource: {
    url: process.env.DIRECT_URL ? env("DIRECT_URL") : env("DATABASE_URL"),
  },
});
